### PR TITLE
Fix errors when building with /permissive- (#42)

### PR DESCRIPTION
**Pull request by jrave**
This should address #42 

Tested that examples and tests build with:
* Current default of VS 2015 and SDK 8.1
* VS 2017 15.6.5, SDK 10.0.16299.0 and /permissive-

### CODE REVIEW

**Comment by zacbrown** [comment]
Thanks for your help! Not sure why I got an error making these changes. Maybe just dirty build.

Could you add the `/permissive-` setting to the NativeExamples and krabstest projects? That'll just ensure the project continues to be compliant with `/permissive-` going forward.

**Comment by zacbrown** [comment]
Hi,

Yes - let's go ahead and upgrade the project toolchain to VS2017 and Win10 SDK.

**Comment by jrave** [comment]
Alright updated the projects and solution to VS 2017 and enabled `/permissive-` for the NativeExamples and  krabstests projects.

There is one caveat with this change:
Boost now throws the following messages: `Unknown compiler version - please run the configure tests and report the results`. Tests run fine so this is likely just an annoyance.

Tried updating to Boost 1.66.0 but that gave the following message along a similar line: `Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.`. So it seemed not worth it to also drag a Boost update into this.

**Comment by zacbrown** [comment]
Thanks!

I missed this the other day so I’ll be taking a look today.

**Pull request merged**
